application: sympy-gamma
version: 2
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application

libraries:
- name: django
  version: "1.3"