application: sympy-gamma-hrd
version: 3
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application

libraries:
- name: django
  version: "1.3"
- name: numpy
  version: "1.6.1"
